---
- name: Disable pass auth
  hosts: appserver:monitoring:gateway
  become: yes

  tasks:
    - name: install open ssh
      apt:
        name: openssh-server
        state: latest
    - name: change permission .ssh
      file:
        path: /home/adminuser/.ssh
        mode: "0755"
    - name: change permission auth key
      file:
        path: /home/adminuser/.ssh/authorized_keys
        mode: "0655"
    - name: Update SSH config pass auth
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
      notify: restart sshd
    - name: pubkey auth
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PubkeyAuthentication"
        line: "PubkeyAuthentication yes"
        state: present
    - name: Uncomment PubkeyAuthentication line
      replace:
        path: /etc/ssh/sshd_config
        regexp: "^#?(PubkeyAuthentication)"
        replace: '\1'
    - name: comment Include /etc/ssh/sshd_config.d/*.conf
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Include /etc/ssh/sshd_config\.d/\*\.conf$'
        line: '# \g<0>'
    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
  handlers:
